import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    String,
    Float,
    DateTime,
    Text,
    Index,
)
from database import Base


def get_utc_now() -> datetime:
    """Helper to return timezone-aware UTC datetime."""
    return datetime.now(timezone.utc)


class SyncDossier(Base):
    """
    SQLAlchemy model representing a Store-and-Forward Dossier
    synced from offline-edge farmer mobile/mesh clients.
    """
    __tablename__ = "sync_dossiers"

    # Primary identifier (UUID string compatible with offline client generation)
    id = Column(
        String(64),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
        doc="Unique identifier generated either offline on edge client or upon sync",
    )

    # Core required fields from prompt specification
    farmer_id = Column(
        String(100),
        nullable=False,
        index=True,
        doc="Identifier of the smallholder coffee farmer (e.g. farmer_noor_01)",
    )
    farmer_name = Column(
        String(100),
        nullable=False,
        default="Noor",
        doc="Name of the farmer",
    )
    crop_type = Column(
        String(100),
        nullable=False,
        doc="Crop variety (e.g., Arabica Bourbon, SL28)",
    )
    offline_diagnosis = Column(
        Text,
        nullable=False,
        doc="Initial diagnosis generated by edge ML / offline rules",
    )
    symptoms_description = Column(
        Text,
        nullable=True,
        doc="Raw field symptom observation entered by the farmer",
    )
    geo_lat = Column(
        Float,
        nullable=False,
        doc="GPS Latitude coordinate of the farm plot",
    )
    geo_lon = Column(
        Float,
        nullable=False,
        doc="GPS Longitude coordinate of the farm plot",
    )
    altitude_m = Column(
        Float,
        nullable=True,
        default=1840.0,
        doc="Altitude in meters above sea level (Ondera highlands)",
    )
    client_recorded_at = Column(
        DateTime(timezone=True),
        nullable=True,
        default=get_utc_now,
        doc="Timestamp when observation was captured offline on the edge node",
    )
    synced_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=get_utc_now,
        index=True,
        doc="Timestamp when payload was received by cloud sync gateway",
    )

    # Claude Orchestrator AI Generated Agronomic Advisory Fields
    advisory_summary = Column(
        Text,
        nullable=True,
        doc="Claude-generated summary tailored for District Extension Officers",
    )
    recommended_action = Column(
        Text,
        nullable=True,
        doc="Prescriptive agronomic action plan (cultural, biological, or chemical)",
    )
    urgency_level = Column(
        String(20),
        nullable=True,
        default="MEDIUM",
        index=True,
        doc="Urgency classification: LOW, MEDIUM, HIGH, CRITICAL",
    )
    market_context = Column(
        Text,
        nullable=True,
        doc="Localized coffee market pricing context and harvest timing advisory",
    )
    status = Column(
        String(20),
        nullable=False,
        default="PROCESSED",
        doc="Dossier status: PENDING, PROCESSED, ESCALATED, RESOLVED",
    )

    # Indexes for fast querying on the extension officer dashboard
    __table_args__ = (
        Index("idx_dossier_farmer_crop", "farmer_id", "crop_type"),
        Index("idx_dossier_synced_urgency", "synced_at", "urgency_level"),
    )

    def __repr__(self) -> str:
        return (
            f"<SyncDossier(id={self.id}, farmer_id={self.farmer_id}, "
            f"crop={self.crop_type}, urgency={self.urgency_level})>"
        )
